### ISSUE TITLE
Why does Packagist point to an outdated fork by Polem

### ISSUE THREAD

**Issue by frickenate** [silexlabs/amfphp-2.0#18]
Why is Packagist configured to use an outdated fork at https://github.com/polem/amfphp-2.0 for the silexlabs/amfphp composer package?

Here's their database lookup: https://packagist.org/packages/silexlabs/amfphp

Should silexlabs/amfphp composer package not be pointing to the silexlabs original repository rather than this polem fork? This seems very fishy.

**Comment by arielsom** [comment]
indeed it should, thanks for pointing that out. What should be done? Contact packagist?

**Comment by frickenate** [comment]
I'm not sure. I would first try to login to packagist with your github account, there might be an option on the package's page to dispute ownership or modify the package. If not, they have a contact email address: contact@packagist.org

**Comment by arielsom** [comment]
Hi, it took a while but it's fixed. thanks!
