### ISSUE TITLE
Discovery service incorrect filename checking

### ISSUE THREAD

**Issue by sfisol** [silexlabs/amfphp-2.0#19]
Editing service file in Vim (or, I believe, some other editors) a swap file is created (.service.php.swp) which brakes discovery service.

It seems discovery service takes all file names containing ".php" instead of file names ending with ".php".

**Comment by sfisol** [comment]
diff -u a/AmfphpDiscoveryService.php b/AmfphpDiscoveryService.php
    --- a/AmfphpDiscoveryService.php        2015-05-07 13:39:31.899583976 +0200
    +++ b/AmfphpDiscoveryService.php        2015-05-07 13:39:42.899991462 +0200
    @@ -67,7 +67,7 @@
             if ($folderContent) {
                 foreach ($folderContent as $fileName) {
                     //add all .php file names, but removing the .php suffix
    -                if (strpos($fileName, '.php')) {
    +                if (preg_match('/.php$/', $fileName)) {
                         $fullServiceName = $subFolder . substr($fileName, 0, strlen($fileName) - 4);
                         $ret[] = $fullServiceName;
                     } else if ((substr($fileName, 0, 1) != '.') && is_dir($rootPath . $subFolder . $fileName)) {

**Comment by arielsom** [comment]
Thanks for pointing that out, I'll test and add you fix as soon as possible

**Comment by arielsom** [comment]
ok it's in the 2.2.2 release that's coming out today or tomorrow
