### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by elvispdosreis** [silexlabs/amfphp-2.0#21]
I'm using, however I'm having a poor performance to return the data.
The amfphp falls into a loop almost infinite, takes too long to process writeAmf3Array

$ret = new stdClass();
$explicitTypeField = Amfphp_Core_Amf_Constants::FIELD_EXPLICIT_TYPE;
$ret->$explicitTypeField = "flex.messaging.io.ArrayCollection";
$ret->source = $yourData;
return $ret;

**Comment by arielsom** [comment]
What does your data look like?

**Comment by arielsom** [comment]
closed
